### PR TITLE
Add init subcommand, improve testing configuration

### LINKED ISSUE #11: clash --init
Hey!

I was just building out Jekyll textile converter and wanted to use clash to run the integration tests, but I'm a little confused on where the configuration should live and when the configuration supersedes the args passed to `clash`, etc.

Rspec has `rspec --init` which creates `spec/spec_helper.rb` and `.rspec`. You know you're all set to write specs from then on out. Maybe a similar feature?

### PR DESCRIPTION
**Pull request by imathis**
Documentation still needs to be updated, but this should close #11 and #13 when merged.

### CODE REVIEW

**Comment by imathis** [comment]
Yo @parkr. It think this is ready to go. I've rewritten the Readme a great deal and I hope it's easier to follow. Things I've done here:

1. Added the `init` subcommand for creating a testing scaffold.
2. Added the option to run tests by line number, e.g. `clash :35`.
3. Added the `--build` flag which can run all your tests, only executing the `before` scripts and Jekyll builds. This is useful if you want to build your all of your test sites and look at the results without having it yell at you about failures.

I've also figured out how to get it out without any breaking changes, so this will be 1.5.0.

Clash config files are now named `_clash.yml` but `.clash.yml` will still work. Also, after trying out the new `build: dir` option to tell Jekyll to build in a specific directory with `-s dir` I decided against it. Instead I added the `dir: some_dir` option which runs anything in the test in the scope of that directory. This works better since sometimes you'll have tests that don't need to build, and acting on paths just never works as well as changing directories.

I know there's a lot to review and I'm not expecting you to pick through every change. I'm mainly curious if you think this presents itself more clearly and is something people will understand better.

Thanks for pushing me to make it better!

**Comment by imathis** [comment]
I'm going to go head and release this as it all seems to work. If you have time to review it, I'll happily receive your suggestions.

**Comment by parkr** [comment]
Great! Sorry it took me a while; the "49 files changed" made me put it off again and again until "I had adequate time" which I only just had. Thanks for doing this! :shipit:

**Comment by imathis** [comment]
Woohoo! I'm already really enjoying the changes. Being able to run a test by typing a line number is really handy.

**Pull request merged**
